export const PRODUCTS=[
  {id:'egg',g:'g0',n:["Яйця (без шкаралупи)", "Eggs (without shell)", "Ovos (sem casca)"],k:143,p:12.6,f:9.5,c:0.7},
  {id:'chk_raw',g:'g0',n:["Куряча грудка, сира", "Chicken breast, raw", "Peito de frango, cru"],k:113,p:23.6,f:1.9,c:0},
  {id:'chk_ck',g:'g0',n:["Куряча грудка, готова", "Chicken breast, cooked", "Peito de frango, cozinhado"],k:165,p:31,f:3.6,c:0},
  {id:'chk_mince',g:'g0',n:["Курячий фарш, сирий", "Chicken mince, raw", "Frango picado, cru"],k:143,p:17.4,f:8.1,c:0},
  {id:'salmon',g:'g0',n:["Лосось, сирий", "Salmon, raw", "Salmão, cru"],k:208,p:20.4,f:13.4,c:0},
  {id:'cod',g:'g0',n:["Тріска, сира", "Cod, raw", "Bacalhau fresco, cru"],k:82,p:17.8,f:0.7,c:0},
  {id:'dorada',g:'g0',n:["Дорада, філе сире", "Sea bream fillet, raw", "Dourada, filete cru"],k:121,p:19.8,f:4.6,c:0},
  {id:'shrimp',g:'g0',n:["Креветки, сирі очищені", "Shrimp, raw peeled", "Camarão, cru descascado"],k:85,p:20.1,f:0.5,c:0},
  {id:'shrimp_ck',g:'g0',n:["Креветки, варені", "Shrimp, cooked", "Camarão, cozido"],k:99,p:24,f:0.3,c:0.2},
  {id:'sardine',g:'g0',n:["Сардини консервовані, без олії", "Canned sardines, no oil", "Sardinhas em lata, sem óleo"],k:208,p:24.6,f:11.5,c:0},
  {id:'veal',g:'g0',n:["Телятина, сира", "Veal, raw", "Vitela, crua"],k:120,p:20.5,f:4.1,c:0},
  {id:'pork',g:'g0',n:["Свинина пісна, сира", "Lean pork, raw", "Porco magro, cru"],k:143,p:21,f:6.5,c:0},
  {id:'liver',g:'g0',n:["Куряча печінка, сира", "Chicken liver, raw", "Fígado de frango, cru"],k:119,p:16.9,f:4.8,c:0.7},
  {id:'pate',g:'g0',n:["Паштет домашній (без масла)", "Homemade pâté (no butter)", "Patê caseiro (sem manteiga)"],k:130,p:17,f:5,c:4},
  {id:'chk_chips',g:'g0',n:["Курячі чіпси «Dry Chicken Hot» (XO)", "Chicken chips \u201CDry Chicken Hot\u201D (XO)", "Chips de frango \u201CDry Chicken Hot\u201D (XO)"],k:294,p:63,f:3.2,c:3.2},
  {id:'aged',g:'g1',n:["Сир витриманий 6–12 міс", "Aged cheese, 6–12 months", "Queijo curado, 6–12 meses"],k:390,p:26,f:31,c:1},
  {id:'parm',g:'g1',n:["Пармезан", "Parmesan", "Parmesão"],k:392,p:36,f:26,c:3},
  {id:'mozz',g:'g1',n:["Моцарела лайт", "Mozzarella light", "Mozzarella light"],k:153,p:17,f:9,c:1},
  {id:'mozz_full',g:'g1',n:["Моцарела звичайна", "Mozzarella, regular", "Mozzarella normal"],k:280,p:18,f:22,c:1},
  {id:'ched',g:'g1',n:["Чедер", "Cheddar", "Cheddar"],k:403,p:23,f:33,c:3},
  {id:'blue',g:'g1',n:["Блакитний сир", "Blue cheese", "Queijo azul"],k:353,p:21.4,f:28.7,c:2.3},
  {id:'milk16',g:'g1',n:["Молоко 1,5–1,8% (мл)", "Milk 1.5–1.8% (ml)", "Leite meio-gordo (ml)"],k:47,p:3.3,f:1.6,c:4.9},
  {id:'milk35',g:'g1',n:["Молоко 3,5% (мл)", "Milk 3.5% (ml)", "Leite gordo (ml)"],k:64,p:3.2,f:3.6,c:4.7},
  {id:'buck',g:'g2',n:["Гречка, суха", "Buckwheat, dry", "Trigo-sarraceno, seco"],k:330,p:12.6,f:3.3,c:62},
  {id:'bulgur',g:'g2',n:["Булгур, сухий", "Bulgur, dry", "Bulgur, seco"],k:340,p:12.3,f:1.3,c:70},
  {id:'basmati',g:'g2',n:["Рис басматі, сухий", "Basmati rice, dry", "Arroz basmati, seco"],k:350,p:8,f:0.6,c:78},
  {id:'sushi',g:'g2',n:["Рис для суші, сухий", "Sushi rice, dry", "Arroz para sushi, seco"],k:355,p:6.5,f:0.5,c:80},
  {id:'rice_ck',g:'g2',n:["Рис, варений", "Rice, cooked", "Arroz, cozido"],k:130,p:2.7,f:0.3,c:28},
  {id:'pasta',g:'g2',n:["Макарони, сухі", "Pasta, dry", "Massa, seca"],k:350,p:12,f:1.5,c:71},
  {id:'pasta_ck',g:'g2',n:["Макарони, варені", "Pasta, cooked", "Massa, cozida"],k:140,p:4.8,f:0.6,c:28.4},
  {id:'potato',g:'g2',n:["Картопля, сира", "Potato, raw", "Batata, crua"],k:77,p:2,f:0.1,c:16.5},
  {id:'bread',g:'g2',n:["Хліб на заквасці", "Sourdough bread", "Pão de massa mãe"],k:260,p:9,f:1.6,c:52},
  {id:'carrot',g:'g3',n:["Морква", "Carrot", "Cenoura"],k:35,p:1.3,f:0.1,c:7},
  {id:'pepper',g:'g3',n:["Перець солодкий", "Bell pepper", "Pimento"],k:27,p:1.3,f:0,c:5.3},
  {id:'tomato',g:'g3',n:["Помідори", "Tomatoes", "Tomate"],k:18,p:0.9,f:0.2,c:2.7},
  {id:'onion',g:'g3',n:["Цибуля", "Onion", "Cebola"],k:40,p:1.1,f:0.1,c:7.6},
  {id:'arugula',g:'g3',n:["Рукола", "Rocket", "Rúcula"],k:25,p:2.6,f:0.7,c:2},
  {id:'cabbage',g:'g3',n:["Капуста білокачанна", "White cabbage", "Couve branca"],k:25,p:1.3,f:0.1,c:3.3},
  {id:'broccoli',g:'g3',n:["Броколі", "Broccoli", "Brócolos"],k:34,p:2.8,f:0.4,c:4},
  {id:'cucumber',g:'g3',n:["Огірок", "Cucumber", "Pepino"],k:15,p:0.7,f:0.1,c:2.9},
  {id:'rasp',g:'g4',n:["Малина", "Raspberries", "Framboesas"],k:45,p:1.2,f:0.7,c:5.5},
  {id:'bluebr',g:'g4',n:["Лохина", "Blueberries", "Mirtilos"],k:57,p:0.7,f:0.3,c:12},
  {id:'plum',g:'g4',n:["Сливи", "Plums", "Ameixas"],k:46,p:0.7,f:0.3,c:10},
  {id:'mango',g:'g4',n:["Манго", "Mango", "Manga"],k:60,p:0.8,f:0.4,c:13.4},
  {id:'avo',g:'g5',n:["Авокадо", "Avocado", "Abacate"],k:160,p:2,f:14.7,c:2},
  {id:'olive_oil',g:'g5',n:["Оливкова олія", "Olive oil", "Azeite"],k:900,p:0,f:100,c:0},
  {id:'olives',g:'g5',n:["Оливки", "Olives", "Azeitonas"],k:145,p:1,f:15,c:0.5},
  {id:'brazil',g:'g5',n:["Бразильський горіх", "Brazil nuts", "Castanha-do-brasil"],k:656,p:14.3,f:66.4,c:4.2},
  {id:'butter',g:'g5',n:["Вершкове масло", "Butter", "Manteiga"],k:717,p:0.9,f:81,c:0.1},
  {id:'veg_oil',g:'g5',n:["Олія рослинна для смаження", "Vegetable oil for frying", "Óleo vegetal para fritar"],k:900,p:0,f:100,c:0},
  {id:'sesame_oil',g:'g5',n:["Кунжутна олія", "Sesame oil", "Óleo de sésamo"],k:900,p:0,f:100,c:0},
  {id:'soy',g:'g6',n:["Соєвий соус", "Soy sauce", "Molho de soja"],k:53,p:8.1,f:0.6,c:4.9},
  {id:'gochu',g:'g6',n:["Гочуджанг", "Gochujang", "Gochujang"],k:220,p:4.5,f:1.5,c:46},
  {id:'chili_oil',g:'g6',n:["Гостра олія", "Chili oil", "Óleo picante"],k:800,p:1,f:87,c:4},
  {id:'sugar',g:'g6',n:["Цукор", "Sugar", "Açúcar"],k:400,p:0,f:0,c:100},
  {id:'honey',g:'g6',n:["Мед", "Honey", "Mel"],k:330,p:0.3,f:0,c:82},
  {id:'matcha',g:'g7',n:["Матча, порошок", "Matcha powder", "Matcha em pó"],k:324,p:30,f:5.3,c:39},
  {id:'mm_pea',g:'g7',n:["M&M's з арахісом", "Peanut M&M's", "M&M's de amendoim"],k:512,p:9.5,f:25,c:60},
  {id:'mm',g:'g7',n:["M&M's класичні", "M&M's classic", "M&M's clássicos"],k:492,p:4.3,f:21,c:71.3},
  {id:'bueno',g:'g7',n:["Kinder Bueno", "Kinder Bueno", "Kinder Bueno"],k:572,p:8.6,f:37.3,c:49.5},
  {id:'kinder',g:'g7',n:["Kinder Chocolate (батончик)", "Kinder Chocolate (bar)", "Kinder Chocolate (barra)"],k:566,p:8.7,f:35,c:53.5},
  {id:'korivka',g:'g7',n:["Цукерка «Корівка»", "\u201CKorivka\u201D fudge candy", "Caramelo \u201CKorivka\u201D"],k:393,p:3.3,f:6.2,c:81},
  {id:'cap16',g:'g9',n:["Капучино на молоці 1,5% (мл)", "Cappuccino, 1.5% milk (ml)", "Cappuccino, leite meio-gordo (ml)"],k:47,p:3.3,f:1.6,c:4.9},
  {id:'cap35',g:'g9',n:["Капучино на молоці 3,5% (мл)", "Cappuccino, 3.5% milk (ml)", "Cappuccino, leite gordo (ml)"],k:64,p:3.2,f:3.6,c:4.7},
  {id:'mat16',g:'g9',n:["Матча лате на молоці 1,5% (мл)", "Matcha latte, 1.5% milk (ml)", "Matcha latte, leite meio-gordo (ml)"],k:52,p:3.8,f:1.7,c:5.6},
  {id:'mat35',g:'g9',n:["Матча лате на молоці 3,5% (мл)", "Matcha latte, 3.5% milk (ml)", "Matcha latte, leite gordo (ml)"],k:69,p:3.7,f:3.7,c:5.4},
  {id:'espresso',g:'g9',n:["Еспресо / чорна кава (мл)", "Espresso / black coffee (ml)", "Expresso / café preto (ml)"],k:2,p:0.1,f:0,c:0},
  {id:'pornstar',g:'g9',n:["Порнстар мартіні (100 = 1 бокал)", "Porn Star Martini (100 = 1 glass)", "Porn Star Martini (100 = 1 copo)"],k:258,p:0.3,f:0,c:24},
  {id:'beer_wheat',g:'g9',n:["Пиво пшеничне, 5% (мл)", "Wheat beer, 5% (ml)", "Cerveja de trigo, 5% (ml)"],k:45,p:0.5,f:0,c:3.5},
  {id:'beer_corona',g:'g9',n:["Пиво Corona Extra (мл)", "Corona Extra beer (ml)", "Cerveja Corona Extra (ml)"],k:42,p:0.3,f:0,c:3.9},
  {id:'asian_est',g:'g8',n:["Азійська страва (оцінка, готова)", "Asian dish (estimate, cooked)", "Prato asiático (estimativa, cozinhado)"],k:150,p:8.5,f:6.5,c:14},
];
